name: musService
services:

  loki:
    restart: always
    # image: grafana/loki:2.9.3
    image: grafana/loki:latest
    volumes:
      - ../Configs/loki-config.yml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - 3100:3100
    depends_on:
      postgres:
        condition: service_healthy

  grafana:
    restart: always
    # image: grafana/grafana:10.1.6
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - ../grafana-data:/var/lib/grafana
    depends_on:
      loki:
        condition: service_started

  postgres:
    container_name: mus_db
    image: postgres:latest
    volumes: 
      - ../postgres-data:/var/lib/postgresql/data    
    environment:
      POSTGRES_DB: musdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d musdb"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - musNet
    restart: unless-stopped
  
  redis:
    container_name: redis
    image: redis
    restart: always
    volumes: 
      - ../redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - musNet
    depends_on:
      postgres:
        condition: service_healthy

networks:
  musNet:
    name: musNet
    driver: bridge
    # external: true
#   logNet:
#     name: logNet
#     driver: bridge
#     external: true
  

volumes:
  postgres-data:
  redis-data:
  grafana-data:  